version: '3'
networks:
  backend:
    driver: bridge

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./.data/conf.d:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    restart: always
    ports:
      - 3006:3306
    networks:
      - backend

  app:
    build: ./dock/python
    container_name: django-container
    tty: true
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8088:8000
    depends_on:
      - db
    networks:
      - backend
